# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e47b52699b2efdeb5c77df5f551bffc202c717047598985211008a95bffe24f2a878c8ea6cf49f3f17c4af387539c3a15a91117bbf7970fa0e1d14acfcf4c44

test:
  secret_key_base: 451fd3a48b8f7f541f6c0f403bf70c6b0280fe94861e3571b7c2cef2faf8588a6c89b603da9db93987bc4c7ac9bbdaad4e2d3439fc289aa057d6652fab44dfd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
